SELECT 10대 남자, 예매율 %
FROM RESERVATION
JOIN MEMBER USING(MEM_NO)
WHERE;

SELECT COUNT(*)
FROM RESERVATION
JOIN MEMBER USING(MEM_NO)
WHERE PAY_STATUS = 'Y'
GROUP BY TO_NUMBER(TO_CHAR(BIRTH_DATE,'YYYY')) - TO_NUMBER(TO_CHAR(SYSDATE,'YYYY'));

SELECT *
FROM(SELECT EXTRACT(YEAR FROM BIRTH_DATE) - EXTRACT(YEAR FROM BIRTH_DATE) "AGE"
        FROM MEMBER)
WHERE AGE BETWEEN 1 AND 100;

SELECT LABEL, (COUNT(*) / (SELECT COUNT(*)
                                  FROM (SELECT  FLOOR((EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM BIRTH_DATE))/10)*10
                                  FROM RESERVATION
                                  JOIN MEMBER USING (MEM_NO)))) * 100 AS "RATE"
FROM (SELECT  FLOOR((EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM BIRTH_DATE))/10)*10||'대'||DECODE(GENDER, 'M', '남성', 'F','여성') AS LABEL
                              FROM RESERVATION
                              JOIN MEMBER USING (MEM_NO))
GROUP BY LABEL;