Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (1,1,1235,'오디오를 안들어서 그런지 모르겠는데 기대보다는 그냥 그랬습니다 그래도 오랜만에 문화생활해서 좋았어요',3,to_date('22/08/01','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (2,2,1234,'전시회 다녀 본 것 중에서 색다르고 새로웠어요. 도슨트가 주말에 없어서 아쉬웠어요. 도슨트의 설명이 필요한 전시예요.. 일하는 사람들은 평일에는 가지도 못하는데.. 주말이나 공휴일 시간날 때 여가생활을 보내는데..',1,to_date('22/08/02','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (3,2,1236,'도슨트가 그때는 운영되지 않아 아쉽네요.. 오디오가이드도 돈을 또 결제해서 들어야 하는 시스템이예요',5,to_date('22/08/04','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (4,3,1237,'경기전은 제 어릴적 추억이기도 하고 우리 아이들이 앞으로 기억해줬으면 하는 곳이기도 합니다.',4,to_date('22/08/10','RR/MM/DD'),'Y');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (5,3,1238,'종종 걸음으로 경기전 구석구석을 다니며 친절한 안내와 즐겁게 맞아 주시는 여러 왕들 덕분에 지루함 1도 없이 너무 행복한 시간이였습니다.',3,to_date('22/08/12','RR/MM/DD'),'Y');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (6,3,1239,'행사가 끝무렵쯤 왕들이 먼저 기념사진도 제안 해 주시고 생각지도 못한고품격의 재즈공연이 감동을 더해 주었습니다. 재즈공연을 처응 접한 아이들이이 날이후 재즈에 대한 관심도 생겼더라구요 좋은 공연 추억 남겨 주셔서 감사합니다.',3,to_date('22/08/13','RR/MM/DD'),'Y');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (10,4,1238,'당시에는 세상에 알려지지 않았던 사진작가 비비안의 따뜻한 시선을 느낄 수 있는 사진전',3,to_date('22/08/17','RR/MM/DD'),'Y');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (11,5,1240,'당시평일에 방문하니 생각보다 집중도 잘되고 좋았어요에는 세상에 알려지지 않았던 사진작가 비비안의 따뜻한 시선을 느낄 수 있는 사진전',2,to_date('22/08/18','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (12,5,1242,'큰 기대없이 방문했으나 생각보다 훨 씬 더 좋았어요. 비비안 마이어 사진전 추천드립니다. 방문하니 생각보다 집중도 잘되고 좋았어요',1,to_date('22/08/19','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (13,6,1243,'즐겁게 관람했습니다.',5,to_date('22/08/20','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (14,6,1246,'인물 사진에서 힘과 시대 특유의 분위기가 느껴졌어요.',4,to_date('22/08/21','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (15,6,1234,'잘 모르는 사진 작가인데 이번 기회에 알게 되어 즐거웠습니다.',3,to_date('22/08/22','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (16,7,1248,'지난 겨울 피크닉에서 본 사울레이터 전시 생각이 많이 났어요. 사진 수도 많고 공간 흐름도 그렇고.. 전시가 정말 알차요! 사진 촬영이 안되는 게 아쉽고 포토존이 생각보다 사진이 예쁘게 안 나와서 아쉬웠지만 그럼에도 정말 좋았어요!',2,to_date('22/08/23','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (17,8,1235,'장내 사진촬영 금지라 동선 막히는 일도 없고 좋았어요.',1,to_date('22/08/24','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (18,8,1237,'포토존 따로 설치해준 것도 센스있고 좋았습니다.',5,to_date('22/08/25','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (19,9,1235,'사진수가 생각보다 적어서 아쉽..',4,to_date('22/08/26','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (21,10,1237,'역사적인 사건에 있는 사진들이여서 좋지만',2,to_date('22/08/28','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (22,11,1250,'색감이 아주 예쁜 전시였습니다.',4,to_date('22/08/29','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (23,11,1260,'작품들도 다양하고 무엇보다 포토존들이 상당히 귀여웠어요.',4,to_date('22/09/02','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (24,11,1264,'즐거운 관람하고 왔습니다.',4,to_date('22/09/03','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (25,12,1255,'번뜩이는 아이디어!!',3,to_date('22/09/04','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (26,12,1237,'재미있는 아이디어가 가득한 세상에 여행다녀온 것 같아요,',3,to_date('22/09/05','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (27,13,1239,'사람이 많았지만 그만큼 포토존도 많고 볼거리 많은 전시였어요 ',2,to_date('22/09/06','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (28,13,1236,'장줄리앙이 직접 DDP에 와서 작업한 비하인드 영상을 보니 더욱 그림을 관심있게 볼 수 있었습니다 ',2,to_date('22/09/07','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (29,13,1247,'아이들과 와도 재밌게 즐길 수 있을 것 같아요 마지막 존의 그림도 너무 좋았습니다 언어의 한계가 아쉬울 뿐이네',3,to_date('22/09/08','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (30,14,1235,'남녀노소 누구나 좋아할만한 전시',1,to_date('22/09/09','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (31,14,1236,'다양한 분위기와 장르의 작품을 즐길 수 있었다.',5,to_date('22/09/10','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (32,15,1234,'친근한 그림들과 다양한 물품들까지, 아이의 호기심과 관심을 끄는대 충분한 좋은 시간을 보냈습니다.',4,to_date('22/09/11','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (33,16,1237,'설명보기전에는 그림인줄알았어요',3,to_date('22/09/12','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (34,16,1237,'전시물도 전시배경도 다 예쁘고 사진도 잘나와요',2,to_date('22/09/15','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (35,17,1238,'그의 작품은 사진인지 회화인지 정말 구분이 힘들 정도로 경이로운 추상적 색채 풍경이 인상적입니다.',1,to_date('22/09/20','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (36,17,1240,'편안한 색의 조합으로 안정되고 따뜻한 느낌을 줍니다.',2,to_date('22/09/22','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (37,18,1246,'프랑코폰타나의 사진을 보고 있으면 사진인 것을 잊어버리고 그림이라고 생각하면서 사진을 봤어요 ',3,to_date('22/09/27','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (38,18,1249,'사진 속 저장소가 현재 지구에 있을까라는 생각이 들 정도로 그가 담아낸 풍경들은 너무나 아름다웠어요 ',4,to_date('22/09/27','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (39,18,1251,'자연풍경 뿐만 아니라 도시, 사람, 빠르게 스쳐지나가는 순간들을 주제로 빛과 강한 색의 대비로 ',5,to_date('22/09/30','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (40,18,1261,'프랑코폰타나만의 색다른 시선으로 사진 속에 담겨져 있어요',4,to_date('22/10/01','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (41,18,1259,'진전이라고 어렵기만 한 것이 아니라 일상이 녹아있기 때문에 ',3,to_date('22/10/02','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (42,19,1262,'전시 기간 내에 몇 번 더 방문할 것 같은 전시회입니다! 프랑코 폰타나의 사진 철학도 알 수 있어서 좋았어요~~!',2,to_date('22/10/02','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (43,19,1263,'한국 최초 회고전이라서 더욱 특별했던 전시가 아닐까 싶어요:) ',1,to_date('22/10/03','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (44,20,1248,'분명 우리 곁에 존재하지만 그동안 보지 못했던 현실의 생생하고 다채로운 색을 새롭게 발견하고 즐기면서 풍경에 대한 새로운 정의를 생각해볼 수 있었던 귀한 시간이었습니다.',4,to_date('22/10/04','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (45,20,1263,'사진에 관심이 많은 분이나 색채 예술의 향연에 흠뻑 빠져보실 분들은 이번 전시 강추합니다.',3,to_date('22/10/05','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (46,21,1248,'전시 좋았어요. 영상도 너무 좋으니 끝까지 보고 오세요!!',5,to_date('22/10/06','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (47,22,1263,'예쁜 색감과 멋진 사진들 덕에 기분 좋게 관람했습니다!',4,to_date('22/10/07','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (48,22,1258,'처음 보고 온 사진전이었는데 인상깊었고, 사진전에 대한 좋은 기억이 생겨 앞으로 더 많은 사진전에 가보고 싶습니다. ',3,to_date('22/10/08','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (49,22,1248,'볼거리가 많으니 여유있게 시간 잡고 가시면 좋을 것 같아요.',2,to_date('22/10/09','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (50,23,1234,'가벼운 마음으로 보러갔는데 35분간 눈을 뗄수없는 영상이었어요.',1,to_date('22/10/10','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (51,23,1235,'3번정도 계속 넋놓고 보게되면서 눈물도 나는 작품도 있었어요.',2,to_date('22/10/11','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (52,23,1236,'영상을 본 후 모네에 대해 다시 자세히 찾아보게 되었답니다',3,to_date('22/10/12','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (53,24,1237,'한 장소에 앉아서 그림을 관람하는 조금은 이색적인 느낌...',4,to_date('22/10/13','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (54,24,1238,'작품에 담긴 설명을 다 들을 수 있어서 좋았다.',5,to_date('22/10/14','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (55,24,1239,'한편의 인생 드라마를 보는듯한 느낌과 아름다운 그림을 감상할 수 있어서 행복한 시간이었다.',4,to_date('22/10/15','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (56,25,1240,'그냥저냥 볼만한데 딱히 인상깊은 부분은 없었던 것 같아요. 굿즈들이 예쁩니다',3,to_date('22/10/16','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (57,26,1241,'볼거리가 다양하진 않지만 웅장하고 영상미가 있던 전시 바닥에 앉아서 봐서 엉덩이가 차가웠다',2,to_date('22/10/17','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (58,27,1242,'미디어 아트로 한 작가의 삶과 그림을 동시에 접하는 기회가 처음이였는데 이렇게도 그림을 볼 수가 있구나 싶어서 매우 인상적이였다.',1,to_date('22/10/18','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (59,27,1243,'모두 앉아서 보는데 자막은 가운데서만 나오니 잘 안보여서 세면 모두 써줬으면 하는 바램이 있다.',2,to_date('22/10/19','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (60,27,1244,'방석도 조금 부족한 감이 있었다.',4,to_date('22/10/20','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (61,27,1245,'2~3번씩 봐도 질리지 않는 멋진 전시이다. 남도에도 내려왔으면 좋겠다.',3,to_date('22/10/21','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (62,28,1246,'고교시절 미술 시간에 들었던 화가 클로드 모네의 작품과 인생을 너무 아름답고 슬프게 잘 보고갑니다.',5,to_date('22/10/22','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (63,28,1247,'교육적이고 힐링되는 시간이었습니다',5,to_date('22/10/23','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (64,29,1248,'공간도 쾌적하고, 뷰도 너무 좋고근처에 구경할곳들도 있어서 처음 도착후 짐을 맞기고 퇴장시간에 맞춰 5층부터 내려오며 구경했어요',3,to_date('22/10/24','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (65,29,1249,'정말 강추합니다 ~ 근처 공간들도 예쁜곳이 많아서 사진찍기 좋아하는 분이면 더더욱 좋을듯!',5,to_date('22/10/25','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (66,30,1250,'좋은 위치에서 관람할 수 있어서 좋으나 가격이 좀 비싸다는 생각이 드네요',4,to_date('22/10/26','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (67,31,1251,'돈주고 예매했는데 앞자리 사운드 너무커서 사람들귀막고 봤네요 애들은 귀아프다하고 중간에 나갔어요',3,to_date('22/10/27','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (68,32,1252,'행사로 이곳 일대 사람들이 정말 많았는데 특별좌석에 앉아서 편하게 관람하니 더 좋았습니다 ',2,to_date('22/10/28','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (69,32,1253,'날씨도 좋고 졸졸 물소리와 어우러지는 미디어아트쇼 꼭 한번 보러가보세요^^',1,to_date('22/10/29','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (70,33,1254,'앞좌석 중 스피커 바로 앞은 소리가 너무 크고 시끄러웠어요.',2,to_date('22/10/30','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (71,33,1255,'무료관람객인 뒷사람들을 위해 소리를 키운것 같은데 돈주고 이용한 관객을 위해서라도 앞좌석 스피커는 신경쓰셔야 할것 같아요.',3,to_date('22/11/01','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (72,33,1256,'저뿐만 아니라 앞자리에 있는 다른 가족들은 귀가 아파서 나갔습니다.',4,to_date('22/11/02','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (73,33,1257,'보다가 귀가 너무 아파서 뒷자리 자리가 비어 앉았는데 1열보다는 2,3열 추천합니다.',5,to_date('22/11/02','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (74,33,1258,'정면뷰라 영상 감상하기엔 최고였습니다.',5,to_date('22/11/03','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (75,34,1259,'노후된 시설과 도서도 별로 없어서 비추합니다.',5,to_date('22/11/03','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (76,35,1260,'이런곳을 이제서야 알다니 음료값으로 입장권이 비싼가 했지만 와서보니 아니네요',4,to_date('22/11/03','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (77,35,1261,'화장실도 깨끗하고 평일이라그런지 자리도 많이있네요',3,to_date('22/11/04','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (78,35,1262,'아쉬운점을 꼭 찾아본다면 구석자리의 책정리와 의자정리가 잘안되어 있었어요.그래도 장점이 훠~얼씬 크네요 ',3,to_date('22/11/04','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (79,35,1263,'자주이용하게 될것같아요',3,to_date('22/11/05','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (82,36,1264,'진짜 너무너무 예쁜 분위기와 예쁜 포토존이 많아 친구랑 같이 힐링도 하고 사진도 많이 찍고 너무너무 좋았음',3,to_date('22/11/03','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (83,37,1234,'친구들과 좋은 추억.. 재밌는 기억 많이 만들었어요.',3,to_date('22/11/04','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (84,38,1235,'컬러별로 포토존이 만들어져 있는데 레드, 화이트완전 강추입니다.사진이 너무 이쁘게 나와요 !!음엔 남자친구랑도 방문해야겠어요.',3,to_date('22/11/03','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (85,39,1237,'첫 날 보러 갔는데 공사가 덜 됐는지 오픈도 안 됐고,뒤늦게 문자 와서 공사 때문에 늦어졌다며 다음에 이용하라 그러고 다시 방문했더니 할인쿠폰 사용도 안 했는데 사용된 쿠폰이라며 티켓 발급도 안 되고 결국 이름이랑 휴대폰 번호 말하고 관람했네요.내 돈 주고 관람하러 간 건데도 왜 이리 불쾌한 걸까요?!',3,to_date('22/11/03','RR/MM/DD'),'N');
Insert into JV.REVIEW (REVIEW_NO,MEM_NO,EX_NO,REVIEW_CONTENT,RATING,REVIEW_DATE,REVIEW_STATUS) values (86,40,1238,'사진찍기 좋은것같아요',3,to_date('22/11/03','RR/MM/DD'),'N');

COMMIT;